export { default as logo } from './svg/logo.svg';
export { default as girl } from './svg/girl.svg';
export { default as git } from './svg/git.svg';
export { default as lotos } from './svg/lotos.svg';
export { default as person } from './svg/person.svg';
export { default as psyho } from './svg/psyho.svg';
export { default as record } from './svg/record.svg';
export { default as header } from './header.jpg';
export { default as logo_png } from './logo.png';
export { default as icon } from './icon.png';
export {default as problem} from './svg/problem.svg';